### ISSUE TITLE
相机界面返回后，native内存一直在增加

### ISSUE THREAD

**Issue by longzhaodz** [TeacherLuo/XJGARSDKDemoApp-Android#1]
你好，在使用XJGARSDK时遇到了几个问题，想咨询一下有没有解决方案
1、有没有录制视频的功能
2、相机界面返回后，native内存一直在增加，有没有解决方案
3、params文件有没有配置说明文件

**Comment by xiaojigou** [comment]
1、相机录制在这个代码里面没有实现，你可以在LuoGLCameraView的onDrawFrame方法中，
filter.onDrawFrame(finalTexture,filter.mGLCubeBuffer,filter.mGLTextureBuffer);
 long timer = System.currentTimeMillis();
这两句代码之间的地方创建一个帧缓存对象，然后将finalTexture按照指定要保存的尺寸渲染到该帧缓存对象中，然后使用glReadPixel读出帧缓存的内容，这样就有了每一帧处理后的图像信息，就可以自行保存成视频了。

2、这个我们之前测试好像没有发现这个问题，我们再测试下看看

3、我们有一个贴纸制作工具的网页，但中间有小bug，所有还没挂出来，过几天就能挂出来了，
先给你举个例子参数说明下：
{
	"kpNum": 68,		//使用人脸关键点个数
	"name": "angel",	//贴纸的名字，需要时英文的
	"partNum": 3,		//贴纸的部件个数、比如帽子、胡子等分离的组件，这里是3，则"parts"有三个部件组成
	"parts": [{		//部件的列表数组
		"alignX": 0,		//该参数暂时没用，后续做固定屏幕上的logo等需要使用这个值来指定位置
		"alignY": 0,		//该参数暂时没用，后续做固定屏幕上的logo等需要使用这个值来指定位置
		"background": true,		//是否是全屏的固定背景
		"fixed": true,			//是否是固定logo，暂时无用
		"folderName": "angelEff", //贴纸部件的目录名字，需要时英文，目录下图片以name_000.png、name_001.png...形式组织
		"frameDuration": 25,	//该部件持续多少个渲染帧
		"frameNum": 25,		//该贴纸部件总共有多少张图片组成
		"height": 531,			//该贴纸图片高度值
		"kpEndInd": 67,		//对齐人脸使用的关键点列表最后一个点在68个关键点中的索引值
		"kpIndList": [0],		//对齐人脸使用的是非连续关键点时，这里列出关键点索引，
		"kpStInd": 17,			//对齐人脸使用的关键点列表第一个点在68个关键点中的索引值
		"kpUseList": false,		//如果为true则"kpEndInd"、与"kpStInd"失效，使用"kpIndList"中列表点对齐； 否则反之。
		"name": "angelEff",		//该部件的名字，需要英文名
		"width": 374,			//该部件图片宽度
		"xOffsetBBX": 0.17836258,	//x方向上，该部件相对于，对齐点列表的边界盒的偏移比例
		"xScaleBBX": 2.1871345,		//x方向上，该部件相对于，对齐点列表的边界盒的缩放比例
		"yOffsetBBX": -0.6418919,	//y方向上，该部件相对于，对齐点列表的边界盒的偏移比例
		"yScaleBBX": 3.587838		//y方向上，该部件相对于，对齐点列表的边界盒的缩放比例
	}, { //下面第二与第三个贴纸与第一个贴纸类似
		"alignX": 0,
		"alignY": 0,
		"background": false,
		"fixed": false,
		"folderName": "Face",
		"frameDuration": 25,
		"frameNum": 25,
		"height": 158,
		"kpEndInd": 67,
		"kpIndList": [0],
		"kpStInd": 17,
		"kpUseList": false,
		"name": "Face",
		"width": 289,
		"xOffsetBBX": -0.0029239766,
		"xScaleBBX": 1.6900585,
		"yOffsetBBX": -0.10135135,
		"yScaleBBX": 1.0675676
	}, {
		"alignX": 0,
		"alignY": 0,
		"background": false,
		"fixed": false,
		"folderName": "Ring",
		"frameDuration": 25,
		"frameNum": 25,
		"height": 100,
		"kpEndInd": 67,
		"kpIndList": [0],
		"kpStInd": 17,
		"kpUseList": false,
		"name": "Ring",
		"width": 200,
		"xOffsetBBX": 0.038011696,
		"xScaleBBX": 1.1695906,
		"yOffsetBBX": 1.2162162,
		"yScaleBBX": 0.6756757
	}]
}

**Comment by longzhaodz** [comment]
好的，明白了，非常感谢

**Comment by longzhaodz** [comment]
native内存问题是因为参数设置错误了XJGArSdkApi.XJGARSDKSetOptimizationMode(0);

**Comment by xiaojigou** [comment]
贴纸制作工具初版已经可以用了：
http://www.xiaojigou.cn 首页-》开发包-》说明文档-》XJGARSDK说明文档

**Comment by zx1411057234** [comment]
> 好的，明白了，非常感谢

你解决了视频录制的问题吗?

**Comment by zx1411057234** [comment]
视频录制的问题能不能说的详细一点啊

**Comment by xiaojigou** [comment]
思想就是处理的图像分辨率通常较高，可以开一个帧缓存将其渲染成低分辨率的图像，然后把图像读出来保存。我们争取在新版本中加入视频录制的Demo吧。

**Comment by zx1411057234** [comment]
我这个问题搞了两天了，能不能把代码贴一下给我，先感谢大神了------------------ 原始邮件 ------------------
发件人: "TeacherLuo"<notifications@github.com>
发送时间: 2019年5月14日(星期二) 凌晨2:06
收件人: "TeacherLuo/XJGARSDKDemoApp-Android"<XJGARSDKDemoApp-Android@noreply.github.com>;
抄送: "zx1411057234"<1411057234@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [TeacherLuo/XJGARSDKDemoApp-Android] 相机界面返回后，native内存一直在增加 (#1)



思想就是处理的图像分辨率通常较高，可以开一个帧缓存将其渲染成低分辨率的图像，然后把图像读出来保存。我们争取在新版本中加入视频录制的Demo吧。
 
&mdash;

**Comment by AIFahim** [comment]
Hi. I cannot capture the image from the app.

**Comment by xiaojigou** [comment]
Maybe you need&nbsp; some permissions.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Md. Asif Iqbal Fahim"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月13日(星期四) 下午2:16
收件人:&nbsp;"xiaojigou/XJGARSDKDemoApp-Android"<XJGARSDKDemoApp-Android@noreply.github.com&gt;;
抄送:&nbsp;"14625354"<14625354@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [xiaojigou/XJGARSDKDemoApp-Android] 相机界面返回后，native内存一直在增加 (#1)




Hi. I cannot capture the image from the app.

**Comment by AIFahim** [comment]
Sir,
Can you share those permissions. We really interested to this project. And
we want to work with that.

**Comment by beingdesi** [comment]
Hello,
Unable to open your site http://www.xiaojigou.cn/
